### ISSUE TITLE
[Back-end] Illegal update on post adds illegal parameters

### ISSUE THREAD

**Issue by Swaggaaa** [SferaDev/HackerNews#41]

**Comment by SferaDev** [comment]
Illegal u dude

**Comment by SferaDev** [comment]
Should be fixed with https://github.com/SferaDev/HackerNews/commit/3e8ec41b13ef86f2630fe2f7c9256e49afffef7e

@Swaggaaa Could you test it?

**Comment by SferaDev** [comment]
https://github.com/SferaDev/HackerNews/commit/3fa9d9f6c5525ec3e6a111774626a483b99e750a

This actually should fix it better. Now base on update check if there's a subtype declared and uses the subtype schema instead of the supertype's.
