### ISSUE TITLE
[Back-end] Invalid JSON should return a 400 Bad Request

### ISSUE THREAD

**Issue by SferaDev** [SferaDev/HackerNews#46]

**Comment by SferaDev** [comment]
Should be fixed with https://github.com/SferaDev/HackerNews/commit/1e551db81d9b42372eec36f5c0f898feac2e57c8

@Swaggaaa Try it please!

**Comment by Swaggaaa** [comment]
Returns a 400 now, but the response is in html. We may need to adapt it towards the API to provide a json response.

**Comment by SferaDev** [comment]
https://github.com/SferaDev/HackerNews/commit/291acb137178167ec74ecede4910ffde0c39ba36
